apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: parcel-info-360
  namespace: fast-platform
  labels:
    platform: fast
    module: core
    domain: gis
    api: parcel-info
    app: ws-360
spec:
  replicas: 2
  template:
    metadata:
      labels:
        platform: fast
        module: core
        domain: gis
        api: parcel-info
        app: ws-360
    spec:
      containers:
      - name: info
        image: eufast/parcel-info-360:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 2
            memory: 2Gi
        env:
        - name: MONGODB_HOST
          value: mongodb.mongodb
        - name: TARGET_DB
          value: fast
        - name: LPIS_COLLECTION
          value: lpis
        - name: FRONTEND_URL_PREFIX
          value: /
        - name: GIS_INFO_SERVICE_HOST
          value: parcel-info-geojson2gisinfo
        - name: GIS_INFO_SERVICE_PORT
          value: "8080"
        - name: SOC_INFO_SERVICE_HOST
          value: parcel-info-geojson2socinfo
        - name: SOC_INFO_SERVICE_PORT
          value: "8080"
        - name: HYDRO_INFO_SERVICE_HOST
          value: parcel-info-geojson2hydroinfo
        - name: HYDRO_INFO_SERVICE_PORT
          value: "8080"
        - name: NATURA2000_INFO_SERVICE_HOST
          value: parcel-info-geojson2naturainfo
        - name: NATURA2000_INFO_SERVICE_PORT
          value: "8080"
        - name: TOPSOIL_INFO_SERVICE_HOST
          value: parcel-info-geojson2topsoilinfo
        - name: TOPSOIL_INFO_SERVICE_PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
