apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
  name: parcel-info-geojson2socinfo
  namespace: fast-platform
  labels:
    platform: fast
    module: core
    domain: gis
    api: parcel-info
    app: geojson2socinfo
spec:
  alias: latest
  description: Get a SOC (Soil Organic Carbon) approximation of a GeoJSON feature
  handler: main:handler
  image: eufast/parcel-info-geojson2socinfo:0.1.0
  replicas: 2
  maxReplicas: 5
  targetCPU: 80
  runtime: python:3.6
  env:
  - name: MONGODB_HOST
    value: "mongodb.mongodb"
  - name: MONGODB_PORT
    value: "27017"
  - name: MONGODB_DB
    value: "fast"
  - name: SOC_MONGODB_COLLECTION
    value: "soc"
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi 
  triggers:
    http:
      kind: http
      maxWorkers: 10
  version: -1
status:
  state: waitingForResourceConfiguration
